# Generated by Django 6.0.4 on 2026-04-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
    ]
