# Generated by Django 6.0.4 on 2026-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Karta', 'verbose_name_plural': 'Kartalar'},
        ),
        migrations.AlterField(
            model_name='card',
            name='expire',
            field=models.CharField(help_text='Format: MM/YY, YYYY-MM yoki MM.YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
